export const CREATE_FILE_REQUEST = 'CREATE_FILE_REQUEST';
export const CREATE_FILE_SUCCESS = 'CREATE_FILE_SUCCESS';
export const CREATE_FILE_FAILURE = 'CREATE_FILE_FAILURE';
export const DROP_FILE = 'DROP_FILE';
export const READ_HISTORY_REQUEST = 'READ_HISTORY_REQUEST';
export const READ_HISTORY_SUCCESS = 'READ_HISTORY_SUCCESS';
export const READ_HISTORY_FAILURE = 'READ_HISTORY_FAILURE';
